---
- name: Deploy React Application
  hosts: master
  gather_facts: false

  vars_files:
    - vars.yml

  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  tasks:

    - name: Generate Deployment YAML
      template:
        src: react_app.yml.j2
        dest: /opt/kube-lab/k8s/react_app.yml

    - name: Apply Deployment
      command: kubectl apply -f k8s/react_app.yml
      args:
        chdir: /opt/kube-lab

    - name: Wait for Deployment
      command: kubectl rollout status deployment/{{ deployment_name }}
      args:
        chdir: /opt/kube-lab


    - name: Display Pods
      command: kubectl get pods -o wide
      register: pods

    - debug:
        var: pods.stdout_lines
