---
# Kubernetes
k8s_namespace: react-dev
kubeconfig: /var/lib/jenkins/.kube/config


# Deployment
deployment_name: react-app
replicas: 2


# Docker
docker_user: mslinux90
image_name: react-k8s
image_tag: latest


# Service
service_name: react-service
service_type: NodePort
service_port: 80
target_port: 80
node_port: 30000


# Resources
cpu_request: "100m"
memory_request: "128Mi"


cpu_limit: "500m"
memory_limit: "512Mi"
